######################################################################
# Automatically generated by qmake (3.0) Thu Aug 17 02:36:41 2017
######################################################################

TEMPLATE = app
TARGET = tiValue
DEFINES += LEVELDB_PLATFORM_POSIX  TIV_GLOBAL_API_LOG NOMINMAX
CONFIG += c++11
QMAKE_CXXFLAGS += -fnon-call-exceptions -std=c++11
INCLUDEPATH += . \
               libraries/include \
               libraries/ \
               fc/include \
               libraries/leveldb/include \
               utilities/include \
               leveldb \
               leveldb/include \
               db/include

# Input
HEADERS += leveldb/db/builder.h \
           leveldb/db/db_impl.h \
           leveldb/db/db_iter.h \
           leveldb/db/dbformat.h \
           leveldb/db/filename.h \
           leveldb/db/log_format.h \
           leveldb/db/log_reader.h \
           leveldb/db/log_writer.h \
           leveldb/db/memtable.h \
           leveldb/db/skiplist.h \
           leveldb/db/snapshot.h \
           leveldb/db/table_cache.h \
           leveldb/db/version_edit.h \
           leveldb/db/version_set.h \
           leveldb/db/write_batch_internal.h \
           leveldb/port/atomic_pointer.h \
           leveldb/port/port.h \
           leveldb/port/port_example.h \
           leveldb/port/port_posix.h \
           leveldb/port/thread_annotations.h \
           leveldb/table/block.h \
           leveldb/table/block_builder.h \
           leveldb/table/filter_block.h \
           leveldb/table/format.h \
           leveldb/table/iterator_wrapper.h \
           leveldb/table/merger.h \
           leveldb/table/two_level_iterator.h \
           leveldb/util/arena.h \
           leveldb/util/coding.h \
           leveldb/util/crc32c.h \
           leveldb/util/hash.h \
           leveldb/util/histogram.h \
           leveldb/util/logging.h \
           leveldb/util/mutexlock.h \
           leveldb/util/posix_logger.h \
           leveldb/util/random.h \
           leveldb/util/testharness.h \
           leveldb/util/testutil.h \
           leveldb/helpers/memenv/memenv.h \
           leveldb/include/leveldb/c.h \
           leveldb/include/leveldb/cache.h \
           leveldb/include/leveldb/comparator.h \
           leveldb/include/leveldb/db.h \
           leveldb/include/leveldb/dumpfile.h \
           leveldb/include/leveldb/env.h \
           leveldb/include/leveldb/filter_policy.h \
           leveldb/include/leveldb/iterator.h \
           leveldb/include/leveldb/options.h \
           leveldb/include/leveldb/slice.h \
           leveldb/include/leveldb/status.h \
           leveldb/include/leveldb/table.h \
           leveldb/include/leveldb/table_builder.h \
           leveldb/include/leveldb/write_batch.h \
           libraries/include/api/ApiMetadata.hpp \
           libraries/include/api/CommonApi.hpp \
           libraries/include/api/ConversionFunctions.hpp \
           libraries/include/api/GlobalApiLogger.hpp \
           libraries/include/blockchain/AccountEntry.hpp \
           libraries/include/blockchain/AccountOperations.hpp \
           libraries/include/blockchain/Address.hpp \
           libraries/include/blockchain/api_extern.hpp \
           libraries/include/blockchain/Asset.hpp \
           libraries/include/blockchain/AssetEntry.hpp \
           libraries/include/blockchain/AssetOperations.hpp \
           libraries/include/blockchain/BalanceEntry.hpp \
           libraries/include/blockchain/BalanceOperations.hpp \
           libraries/include/blockchain/Block.hpp \
           libraries/include/blockchain/BlockEntry.hpp \
           libraries/include/blockchain/ChainDatabase.hpp \
           libraries/include/blockchain/ChainDatabaseImpl.hpp \
           libraries/include/blockchain/ChainInterface.hpp \
           libraries/include/blockchain/Checkpoints.hpp \
           libraries/include/blockchain/Condition.hpp \
           libraries/include/blockchain/Config.hpp \
           libraries/include/blockchain/ContractEntry.hpp \
           libraries/include/blockchain/ContractOperations.hpp \
           libraries/include/blockchain/DelegateConfig.hpp \
           libraries/include/blockchain/EventOperations.hpp \
           libraries/include/blockchain/Exceptions.hpp \
           libraries/include/blockchain/ExtendedAddress.hpp \
           libraries/include/blockchain/FileStoreEntry.hpp \
           libraries/include/blockchain/FileStoreOperations.hpp \
           libraries/include/blockchain/ForkBlocks.hpp \
           libraries/include/blockchain/GenesisJson.hpp \
           libraries/include/blockchain/GenesisState.hpp \
           libraries/include/blockchain/GluaChainApi.hpp \
           libraries/include/blockchain/ImessageOperations.hpp \
           libraries/include/blockchain/OperationFactory.hpp \
           libraries/include/blockchain/Operations.hpp \
           libraries/include/blockchain/PendingChainState.hpp \
           libraries/include/blockchain/PropertyEntry.hpp \
           libraries/include/blockchain/PtsAddress.hpp \
           libraries/include/blockchain/SlateEntry.hpp \
           libraries/include/blockchain/SlateOperations.hpp \
           libraries/include/blockchain/SlotEntry.hpp \
           libraries/include/blockchain/StorageOperations.hpp \
           libraries/include/blockchain/StorageTypes.hpp \
           libraries/include/blockchain/Time.hpp \
           libraries/include/blockchain/Transaction.hpp \
           libraries/include/blockchain/TransactionCreationState.hpp \
           libraries/include/blockchain/TransactionEntry.hpp \
           libraries/include/blockchain/TransactionEvaluationState.hpp \
           libraries/include/blockchain/TransactionOperations.hpp \
           libraries/include/blockchain/Types.hpp \
           libraries/include/blockchain/WithdrawTypes.hpp \
           libraries/include/cli/Cli.hpp \
           libraries/include/cli/locale.hpp \
           libraries/include/cli/Pretty.hpp \
           libraries/include/cli/PrintResult.hpp \
           libraries/include/client/ApiLogger.hpp \
           libraries/include/client/Client.hpp \
           libraries/include/client/ClientImpl.hpp \
           libraries/include/client/Messages.hpp \
           libraries/include/client/Notifier.hpp \
           libraries/include/client/SeedNodes.hpp \
           libraries/include/db/CachedLevelMap.hpp \
           libraries/include/db/Exception.hpp \
           libraries/include/db/FastLevelMap.hpp \
           libraries/include/db/FsHashMap.hpp \
           libraries/include/db/Fwd.hpp \
           libraries/include/db/LevelMap.hpp \
           libraries/include/db/LevelPodMap.hpp \
           libraries/include/db/UpgradeLeveldb.hpp \
           libraries/include/glua/exceptions.h \
           libraries/include/glua/glua_api_types.h \
           libraries/include/glua/glua_astparser.h \
           libraries/include/glua/glua_common.h \
           libraries/include/glua/glua_compat.h \
           libraries/include/glua/glua_debug_file.h \
           libraries/include/glua/glua_decompile.h \
           libraries/include/glua/glua_disassemble.h \
           libraries/include/glua/glua_loader.h \
           libraries/include/glua/glua_lutil.h \
           libraries/include/glua/glua_parser.h \
           libraries/include/glua/glua_proto_info.h \
           libraries/include/glua/glua_statement.h \
           libraries/include/glua/glua_structs.h \
           libraries/include/glua/glua_tokenparser.h \
           libraries/include/glua/glua_vm.h \
           libraries/include/glua/lapi.h \
           libraries/include/glua/lauxlib.h \
           libraries/include/glua/lcode.h \
           libraries/include/glua/lcompile.h \
           libraries/include/glua/lctype.h \
           libraries/include/glua/ldebug.h \
           libraries/include/glua/ldo.h \
           libraries/include/glua/lfunc.h \
           libraries/include/glua/lgc.h \
           libraries/include/glua/lhashmap.h \
           libraries/include/glua/llex.h \
           libraries/include/glua/llimits.h \
           libraries/include/glua/lmem.h \
           libraries/include/glua/lnetlib.h \
           libraries/include/glua/lobject.h \
           libraries/include/glua/lopcodes.h \
           libraries/include/glua/lparser.h \
           libraries/include/glua/lparsercombinator.h \
           libraries/include/glua/lprefix.h \
           libraries/include/glua/lremote_debugger.h \
           libraries/include/glua/lrepl.h \
           libraries/include/glua/lstate.h \
           libraries/include/glua/lstring.h \
           libraries/include/glua/ltable.h \
           libraries/include/glua/ltm.h \
           libraries/include/glua/ltype_checker_type_info.h \
           libraries/include/glua/ltypechecker.h \
           libraries/include/glua/lua.h \
           libraries/include/glua/lua.hpp \
           libraries/include/glua/luaconf.h \
           libraries/include/glua/lualib.h \
           libraries/include/glua/lundump.h \
           libraries/include/glua/lvm.h \
           libraries/include/glua/lzio.h \
           libraries/include/glua/tichain_lua_api.h \
           libraries/include/glua/tichain_lua_lib.h \
           libraries/include/glua/tichainlib.h \
           libraries/include/net/ChainConnection.hpp \
           libraries/include/net/ChainDownloader.hpp \
           libraries/include/net/ChainMessages.hpp \
           libraries/include/net/ChainServer.hpp \
           libraries/include/net/ChainServerCommands.hpp \
           libraries/include/net/Config.hpp \
           libraries/include/net/Connection.hpp \
           libraries/include/net/CoreMessages.hpp \
           libraries/include/net/Exceptions.hpp \
           libraries/include/net/Message.hpp \
           libraries/include/net/MessageOrientedConnection.hpp \
           libraries/include/net/Node.hpp \
           libraries/include/net/PeerConnection.hpp \
           libraries/include/net/PeerDatabase.hpp \
           libraries/include/net/StcpSocket.hpp \
           libraries/include/net/Upnp.hpp \
           libraries/include/rpc/Exceptions.hpp \
           libraries/include/rpc/RpcClient.hpp \
           libraries/include/rpc/RpcClientApi.hpp \
           libraries/include/rpc/RpcServer.hpp \
           libraries/include/rpc_stubs/CommonApiClient.hpp \
           libraries/include/rpc_stubs/CommonApiRpcClient.hpp \
           libraries/include/rpc_stubs/CommonApiRpcServer.hpp \
           libraries/include/wallet/Config.hpp \
           libraries/include/wallet/Exceptions.hpp \
           libraries/include/wallet/Pretty.hpp \
           libraries/include/wallet/TransactionBuilder.hpp \
           libraries/include/wallet/Url.hpp \
           libraries/include/wallet/Wallet.hpp \
           libraries/include/wallet/WalletDb.hpp \
           libraries/include/wallet/WalletEntrys.hpp \
           libraries/include/wallet/WalletImpl.hpp \
           libraries/leveldb/db/builder.h \
           libraries/leveldb/db/db_impl.h \
           libraries/leveldb/db/db_iter.h \
           libraries/leveldb/db/dbformat.h \
           libraries/leveldb/db/filename.h \
           libraries/leveldb/db/log_format.h \
           libraries/leveldb/db/log_reader.h \
           libraries/leveldb/db/log_writer.h \
           libraries/leveldb/db/memtable.h \
           libraries/leveldb/db/skiplist.h \
           libraries/leveldb/db/snapshot.h \
           libraries/leveldb/db/table_cache.h \
           libraries/leveldb/db/version_edit.h \
           libraries/leveldb/db/version_set.h \
           libraries/leveldb/db/write_batch_internal.h \
           libraries/leveldb/port/atomic_pointer.h \
           libraries/leveldb/port/port.h \
           libraries/leveldb/port/port_example.h \
           libraries/leveldb/port/port_posix.h \
           libraries/leveldb/port/thread_annotations.h \
           libraries/leveldb/table/block.h \
           libraries/leveldb/table/block_builder.h \
           libraries/leveldb/table/filter_block.h \
           libraries/leveldb/table/format.h \
           libraries/leveldb/table/iterator_wrapper.h \
           libraries/leveldb/table/merger.h \
           libraries/leveldb/table/two_level_iterator.h \
           libraries/leveldb/util/arena.h \
           libraries/leveldb/util/coding.h \
           libraries/leveldb/util/crc32c.h \
           libraries/leveldb/util/hash.h \
           libraries/leveldb/util/histogram.h \
           libraries/leveldb/util/logging.h \
           libraries/leveldb/util/mutexlock.h \
           libraries/leveldb/util/posix_logger.h \
           libraries/leveldb/util/random.h \
           libraries/leveldb/util/testharness.h \
           libraries/leveldb/util/testutil.h \
           db/include/bts/db/cached_level_map.hpp \
           db/include/bts/db/exception.hpp \
           db/include/bts/db/fast_level_map.hpp \
           db/include/bts/db/level_map.hpp \
           db/include/bts/db/level_pod_map.hpp \
           db/include/bts/db/upgrade_leveldb.hpp \
           libraries/leveldb/helpers/memenv/memenv.h \
           libraries/leveldb/include/leveldb/c.h \
           libraries/leveldb/include/leveldb/cache.h \
           libraries/leveldb/include/leveldb/comparator.h \
           libraries/leveldb/include/leveldb/db.h \
           libraries/leveldb/include/leveldb/dumpfile.h \
           libraries/leveldb/include/leveldb/env.h \
           libraries/leveldb/include/leveldb/filter_policy.h \
           libraries/leveldb/include/leveldb/iterator.h \
           libraries/leveldb/include/leveldb/options.h \
           libraries/leveldb/include/leveldb/slice.h \
           libraries/leveldb/include/leveldb/status.h \
           libraries/leveldb/include/leveldb/table.h \
           libraries/leveldb/include/leveldb/table_builder.h \
           libraries/leveldb/include/leveldb/write_batch.h \
           utilities/include/bts/utilities/git_revision.hpp \
           utilities/include/bts/utilities/key_conversion.hpp \
           utilities/include/bts/utilities/padding_ostream.hpp \
           utilities/include/bts/utilities/string_escape.hpp \
           utilities/include/bts/utilities/words.hpp \
    libraries/include/blockchain/FileStoreEntry.hpp
     

SOURCES += main.cpp \
           db/upgrade_leveldb.cpp \
           libraries/api/ConversionFunctions.cpp \
           libraries/api/GlobalApiLogger.cpp \
           libraries/blockchain/AccountEntry.cpp \
           libraries/blockchain/AccountOperations.cpp \
           libraries/blockchain/Address.cpp \
           libraries/blockchain/Asset.cpp \
           libraries/blockchain/AssetEntry.cpp \
           libraries/blockchain/AssetOperations.cpp \
           libraries/blockchain/BalanceEntry.cpp \
           libraries/blockchain/BalanceOperations.cpp \
           libraries/blockchain/Block.cpp \
           libraries/blockchain/ChainDatabase.cpp \
           libraries/blockchain/ChainInterface.cpp \
           libraries/blockchain/ContractEntry.cpp \
           libraries/blockchain/ContractOperations.cpp \
           libraries/blockchain/EventOperations.cpp \
           libraries/blockchain/ExtendedAddress.cpp \
           libraries/blockchain/ForkBlocks.cpp \
           libraries/blockchain/GenesisJson_test.cpp \
           libraries/blockchain/ImessageOperations.cpp \
           libraries/blockchain/FileStoreEntry.cpp \
           libraries/blockchain/FileStoreOperations.cpp \
           libraries/blockchain/Operations.cpp \
           libraries/blockchain/PendingChainState.cpp \
           libraries/blockchain/PropertyEntry.cpp \
           libraries/blockchain/PtsAddress.cpp \
           libraries/blockchain/SlateEntry.cpp \
           libraries/blockchain/SlateOperations.cpp \
           libraries/blockchain/SlotEntry.cpp \
           libraries/blockchain/StorageOperations.cpp \
           libraries/blockchain/StorageTypes.cpp \
           libraries/blockchain/tichain_lua_api.cpp \
           libraries/blockchain/Time.cpp \
           libraries/blockchain/Transaction.cpp \
           libraries/blockchain/TransactionCreationState.cpp \
           libraries/blockchain/TransactionEntry.cpp \
           libraries/blockchain/TransactionEvaluationState.cpp \
           libraries/blockchain/TransactionOperations.cpp \
           libraries/blockchain/Types.cpp \
           libraries/blockchain/WithdrawTypes.cpp \
           libraries/cli/Cli.cpp \
           libraries/cli/Pretty.cpp \
           libraries/cli/PrintResult.cpp \
           libraries/client/ApiLogger.cpp \
           libraries/client/BlockchainApi.cpp \
           libraries/client/Client.cpp \
           libraries/client/ContractApi.cpp \
           libraries/client/DebugApi.cpp \
           libraries/client/DelegateApi.cpp \
           libraries/client/GeneralApi.cpp \
           libraries/client/Messages.cpp \
           libraries/client/NetworkApi.cpp \
           libraries/client/Notifier.cpp \
           libraries/client/SandboxContractApi.cpp \
           libraries/client/ScriptApi.cpp \
           libraries/client/WalletApi.cpp \
           libraries/client/TichainApi.cpp \
           libraries/db/UpgradeLeveldb.cpp \
           libraries/glua/glua_api_types.cpp \
           libraries/glua/glua_astparser.cpp \
           libraries/glua/glua_debug_file.cpp \
           libraries/glua/glua_decompile.cpp \
           libraries/glua/glua_disassemble.cpp \
           libraries/glua/glua_loader.cpp \
           libraries/glua/glua_lutil.cpp \
           libraries/glua/glua_proto_info.cpp \
           libraries/glua/glua_state_scope.cpp \
           libraries/glua/glua_statement.cpp \
           libraries/glua/glua_structs.cpp \
           libraries/glua/glua_tokenparser.cpp \
           libraries/glua/glua_vm.cpp \
           libraries/glua/language_server.cpp \
           libraries/glua/lapi.cpp \
           libraries/glua/lauxlib.cpp \
           libraries/glua/lbaselib.cpp \
           libraries/glua/lbitlib.cpp \
           libraries/glua/lcode.cpp \
           libraries/glua/lcompile.cpp \
           libraries/glua/lcorolib.cpp \
           libraries/glua/lctype.cpp \
           libraries/glua/ldblib.cpp \
           libraries/glua/ldebug.cpp \
           libraries/glua/ldo.cpp \
           libraries/glua/ldump.cpp \
           libraries/glua/lfunc.cpp \
           libraries/glua/lgc.cpp \
           libraries/glua/lhashmap.cpp \
           libraries/glua/lhttplib.cpp \
           libraries/glua/linit.cpp \
           libraries/glua/liolib.cpp \
           libraries/glua/ljsonlib.cpp \
           libraries/glua/ljsonrpclib.cpp \
           libraries/glua/llex.cpp \
           libraries/glua/lmathlib.cpp \
           libraries/glua/lmem.cpp \
           libraries/glua/lnetlib.cpp \
           libraries/glua/loadlib.cpp \
           libraries/glua/lobject.cpp \
           libraries/glua/lopcodes.cpp \
           libraries/glua/loslib.cpp \
           libraries/glua/lparser.cpp \
           libraries/glua/lparsercombinator.cpp \
           libraries/glua/lprefix.cpp \
           libraries/glua/lremote_debugger.cpp \
           libraries/glua/lrepl.cpp \
           libraries/glua/lstate.cpp \
           libraries/glua/lstring.cpp \
           libraries/glua/lstrlib.cpp \
           libraries/glua/ltable.cpp \
           libraries/glua/ltablib.cpp \
           libraries/glua/ltimelib.cpp \
           libraries/glua/ltm.cpp \
           libraries/glua/ltype_checker_type_info.cpp \
           libraries/glua/ltypechecker.cpp \
           libraries/glua/lua.cpp \
           libraries/glua/luac.cpp \
           libraries/glua/lundump.cpp \
           libraries/glua/lutf8lib.cpp \
           libraries/glua/lvm.cpp \
           libraries/glua/lzio.cpp \
           libraries/glua/tichain_lua_lib.cpp \
           libraries/glua/tichainlib.cpp \
           libraries/net/ChainDownloader.cpp \
           libraries/net/ChainServer.cpp \
           libraries/net/CoreMessages.cpp \
           libraries/net/MessageOrientedConnection.cpp \
           libraries/net/Node.cpp \
           libraries/net/PeerConnection.cpp \
           libraries/net/PeerDatabase.cpp \
           libraries/net/StcpSocket.cpp \
           libraries/net/Upnp.cpp \
           libraries/rpc/RpcClient.cpp \
           libraries/rpc/RpcServer.cpp \
           libraries/rpc_stubs/CommonApiClient.cpp \
           libraries/rpc_stubs/CommonApiRpcClient.cpp \
           libraries/rpc_stubs/CommonApiRpcServer.cpp \
           libraries/utilities/CommonApi.cpp \
           libraries/utilities/GitRevision.cpp \
           libraries/utilities/KeyConversion.cpp \
           libraries/utilities/StringEscape.cpp \
           libraries/utilities/Words.cpp \
           libraries/wallet/Login.cpp \
           libraries/wallet/TransactionBuilder.cpp \
           libraries/wallet/TransactionLedger.cpp \
           libraries/wallet/TransactionLedgerExperimental.cpp \
           libraries/wallet/Wallet.cpp \
           libraries/wallet/WalletDb.cpp \
           libraries/wallet/WalletEntrys.cpp \
           libraries/leveldb/db/c.cc \
           libraries/leveldb/db/db_impl.cc \
           libraries/leveldb/db/db_iter.cc \
           libraries/leveldb/db/dbformat.cc \
           libraries/leveldb/db/dumpfile.cc \
           libraries/leveldb/db/filename.cc \
           libraries/leveldb/db/log_reader.cc \
           libraries/leveldb/db/log_writer.cc \
           libraries/leveldb/db/memtable.cc \
           libraries/leveldb/db/repair.cc \
           libraries/leveldb/db/table_cache.cc \
           libraries/leveldb/db/version_edit.cc \
           libraries/leveldb/db/version_set.cc \
           libraries/leveldb/db/write_batch.cc \
           libraries/leveldb/port/port_posix.cc \
           libraries/leveldb/table/block.cc \
           libraries/leveldb/table/block_builder.cc \
           libraries/leveldb/table/filter_block.cc \
           libraries/leveldb/table/format.cc \
           libraries/leveldb/table/iterator.cc \
           libraries/leveldb/table/merger.cc \
           libraries/leveldb/table/table.cc \
           libraries/leveldb/table/table_builder.cc \
           libraries/leveldb/table/two_level_iterator.cc \
           libraries/leveldb/util/arena.cc \
           libraries/leveldb/util/bloom.cc \
           libraries/leveldb/util/cache.cc \
           libraries/leveldb/util/coding.cc \
           libraries/leveldb/util/comparator.cc \
           libraries/leveldb/util/crc32c.cc \
           libraries/leveldb/util/env.cc \
           libraries/leveldb/util/env_posix.cc \
           libraries/leveldb/util/filter_policy.cc \
           libraries/leveldb/util/hash.cc \
           libraries/leveldb/util/histogram.cc \
           libraries/leveldb/util/logging.cc \
           libraries/leveldb/util/options.cc \
           libraries/leveldb/util/status.cc \
    libraries/contract_engine/contract_engine.cpp \
    libraries/contract_engine/contract_engine_builder.cpp \
    libraries/contract_engine/glua_contract_engine.cpp \
    libraries/blockchain/GenesisJson.cpp
          

win32:CONFIG(release, debug|release): LIBS += -L$$PWD/../fc/build/release/ -lfc
else:win32:CONFIG(debug, debug|release): LIBS += -L$$PWD/../fc/build/debug/ -lfc
else:unix: LIBS += -L$$PWD/../fc/build/

INCLUDEPATH += $$PWD/../fc/build
DEPENDPATH += $$PWD/../fc/build

 LIBS += ./lib/libfc.a
 LIBS += /usr/lib/x86_64-linux-gnu/libboost_atomic.a
 LIBS += /usr/lib/x86_64-linux-gnu/libboost_chrono.a
 LIBS += /usr/lib/x86_64-linux-gnu/libboost_context.a
 LIBS += /usr/lib/x86_64-linux-gnu/libboost_coroutine.a
 LIBS += /usr/lib/x86_64-linux-gnu/libboost_date_time.a
 LIBS += /usr/lib/x86_64-linux-gnu/libboost_exception.a
 LIBS += /usr/lib/x86_64-linux-gnu/libboost_filesystem.a
 LIBS += /usr/lib/x86_64-linux-gnu/libboost_graph_parallel.a
 LIBS += /usr/lib/x86_64-linux-gnu/libboost_iostreams.a
 LIBS += /usr/lib/x86_64-linux-gnu/libboost_locale.a
 LIBS += /usr/lib/x86_64-linux-gnu/libboost_log.a
 LIBS += /usr/lib/x86_64-linux-gnu/libboost_log_setup.a
 LIBS += /usr/lib/x86_64-linux-gnu/libboost_math_c99.a
 LIBS += /usr/lib/x86_64-linux-gnu/libboost_math_c99f.a
 LIBS += /usr/lib/x86_64-linux-gnu/libboost_math_c99l.a
 LIBS += /usr/lib/x86_64-linux-gnu/libboost_math_tr1.a
 LIBS += /usr/lib/x86_64-linux-gnu/libboost_math_tr1f.a
 LIBS += /usr/lib/x86_64-linux-gnu/libboost_locale.a
 LIBS += /usr/lib/x86_64-linux-gnu/libboost_math_tr1l.a
 LIBS += /usr/lib/x86_64-linux-gnu/libboost_mpi.a
 LIBS += /usr/lib/x86_64-linux-gnu/libboost_mpi_python.a
 LIBS += /usr/lib/x86_64-linux-gnu/libboost_mpi_python-py27.a
exists( /usr/lib/x86_64-linux-gnu/libboost_mpi_python-py34.a ) {
 LIBS += /usr/lib/x86_64-linux-gnu/libboost_mpi_python-py34.a
}
exists( /usr/lib/x86_64-linux-gnu/libboost_mpi_python-py35.a ) {
 LIBS += /usr/lib/x86_64-linux-gnu/libboost_mpi_python-py35.a
}
 LIBS += /usr/lib/x86_64-linux-gnu/libboost_prg_exec_monitor.a
 LIBS += /usr/lib/x86_64-linux-gnu/libboost_program_options.a
 LIBS += /usr/lib/x86_64-linux-gnu/libboost_python.a
 LIBS += /usr/lib/x86_64-linux-gnu/libboost_python-py27.a
exists( /usr/lib/x86_64-linux-gnu/libboost_python-py34.a ) {
 LIBS += /usr/lib/x86_64-linux-gnu/libboost_python-py34.a
}
exists( /usr/lib/x86_64-linux-gnu/libboost_python-py35.a ) {
 LIBS += /usr/lib/x86_64-linux-gnu/libboost_python-py35.a
}
 LIBS += /usr/lib/x86_64-linux-gnu/libboost_random.a
 LIBS += /usr/lib/x86_64-linux-gnu/libboost_regex.a
 LIBS += /usr/lib/x86_64-linux-gnu/libboost_serialization.a
 LIBS += /usr/lib/x86_64-linux-gnu/libboost_signals.a
 LIBS += /usr/lib/x86_64-linux-gnu/libboost_system.a
 LIBS += /usr/lib/x86_64-linux-gnu/libboost_test_exec_monitor.a
 LIBS += /usr/lib/x86_64-linux-gnu/libboost_thread.a
 LIBS += /usr/lib/x86_64-linux-gnu/libboost_timer.a
 LIBS += /usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.a
 LIBS += /usr/lib/x86_64-linux-gnu/libboost_wave.a
 LIBS += /usr/lib/x86_64-linux-gnu/libboost_wserialization.a
 LIBS += /usr/lib/x86_64-linux-gnu/libssl.a
 #LIBS += /usr/lib/x86_64-linux-gnu/libcrypt.a
 LIBS += /usr/lib/x86_64-linux-gnu/libcrypto.a
 #LIBS += /usr/lib/x86_64-linux-gnu/libminiupnpc.a
exists( /usr/lib/libminiupnpc.a ) {
 LIBS += /usr/lib/libminiupnpc.a
} 
exists( /usr/lib/x86_64-linux-gnu/libminiupnpc.a ) {
 LIBS += /usr/lib/x86_64-linux-gnu/libminiupnpc.a
} 
 LIBS += ./lib/libeasylzma_static.a
 LIBS += ./lib/libleveldb.a
 #LIBS += ./lib/libcrypto.a
 #LIBS += ./lib/libssl.a
 #LIBS += ./lib/libminiupnpc.a
 LIBS += /usr/lib/x86_64-linux-gnu/libdl.so
 CONFIG += dll
 QT -= gui core
 LIBS -= -lQtGui -lQtCore
INCLUDEPATH += $$PWD/../../../../usr/lib/x86_64-linux-gnu
DEPENDPATH += $$PWD/../../../../usr/lib/x86_64-linux-gnu


